version: "3.7"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
  api:
    container_name: "api"
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - custom
networks:
  custom:
    driver: bridge
